### PR TITLE
fix compilation and release rust v0.1.3

### PR DESCRIPTION
**Pull request by drahnr**
Removes `threads.h` in order to make `coz` compile on recent fedora - also bumps `coz-rs` crate version to v0.1.3 (please do a release, so `coz::scoped` can be used more easily - which is super handy if you are dealing with legacy async code :) cc @alexcrichton )

### CODE REVIEW

**Comment by drahnr** [comment]
To complete the release a `cargo release` would be required to make it available to a wider audience. Thanks!

**Comment by emeryberger** [comment]
@alexcrichton can you do this? Thanks!

**Comment by drahnr** [comment]
@alexcrichton if you don't feel like doing this, I'd be fine if you add me as co-owner to the crate, otherwise I just keep maintaining `coz-temporary`

**Comment by alexcrichton** [comment]
@drahnr I've invited you to the [crates.io crate](https://crates.io/crates/coz). Want to test out making a release to make sure it works?

**Comment by drahnr** [comment]
Created the v0.1.3 release, thanks!

**Pull request merged**
